Cd(__DIR__);;
#include "Diff"
#include "Find"
#include "HeapLog"
#include "LineRep"
#include "LinkChk"
#include "MemRep"
#include "Merge"
#include "Profiler"
#include "StrUtils"
#include "DocUtils"
#include "ToDolDoc"
#include "ToTXT"
#include "TOS"
Cd("..");;
