//Change anything you want in this
//acct file or others.

//This makes your keyboard fast
SetTypeMatic(0);

//Set Time Zone
local_time_offset=0*60*60*CDATE_FREQ; //Do daylight savings by hand

//$AN,"","mouse_move_scale"$adjust these to set mouse move scale
mxx_scale=0.5;
myy_scale=0.5;
mzz_scale=1.0; //wheel

//don't change these
mxx_prescale=mxx/mxx_scale;
myy_prescale=myy/myy_scale;
mzz_prescale=mzz/mzz_scale;

