#help_index "Games"

Cd("/SparrowOS/Apps/AfterEgypt");;
#include "/SparrowOS/Apps/HolySpirit/HolySpirit.CPP.Z"
#include "Comics.CPP.Z"
#include "/SparrowOS/Demo/Graphics/Camp.CPP.Z"
#include "/SparrowOS/Demo/MultiCore/Clouds.CPP.Z"
#include "/SparrowOS/Demo/Graphics/Mountain.CPP.Z"
#include "Map.CPP.Z"
#include "Battle.CPP.Z"
#include "WaterRock.CPP.Z"
#include "Quail.CPP.Z"
#include "Horeb.CPP.Z"
#include "AfterEgypt.CPP.Z"

#help_index ""
